#install.packages("gifski")


library(gifski)
library(tidyverse)
library(gganimate)
library(gapminder)
#conflict_prefer("arrange", "dplyr") 
#conflict_prefer("mutate", "dplyr") 

sgsp_plus_g = sgsp_plus %>% filter(item == "아몬드류")
animate(anim_plot(sgsp_plus_g, 2015) , 200, fps = 10, duration = 40, width = 1200, height = 800, renderer = gifski_renderer("sgsp_total.gif"))



## 예제

theme_set(theme_classic())

gdp <- read.csv("https://raw.github.com/datasets/gdp/master/data/gdp.csv")
words <- scan(
  text="world income only total dividend asia euro america africa oecd",
  what= character())
pattern <- paste0("(",words,")",collapse="|")
gdp  <- subset(gdp, !grepl(pattern, Country.Name , ignore.case = TRUE))
colnames(gdp) <- gsub("Country.Name", "country", colnames(gdp))
colnames(gdp) <- gsub("Country.Code", "code", colnames(gdp))
colnames(gdp) <- gsub("Value", "value", colnames(gdp))
colnames(gdp) <- gsub("Year", "year", colnames(gdp))

gdp$value <- round(gdp$value/1e9)

#conflict_prefer("mutate", "dplyr")
gap <- gdp %>%
  group_by(year) %>%
  # The * 1 makes it possible to have non-integer ranks while sliding
  mutate(rank = min_rank(-value) * 1,
         Value_rel = value/value[rank==1],
         Value_lbl = paste0(" ",value)) %>%
  filter(rank <=10) %>%
  ungroup()

gap %>% str()

p <- ggplot(gap, aes(rank, group = country, 
                     fill = as.factor(country), color = as.factor(country))) +
  geom_tile(aes(y = value/2,
                height = value,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(country, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=value,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "GDP in billion USD",
       caption = "Sources: World Bank | Plot generated by Nitish K. Mishra @nitishimtech") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,1,1,4, "cm")) +
  
  transition_states(year, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

p

animate(p, 200, fps = 10, duration = 40, width = 800, height = 600, renderer = gifski_renderer("gganim.gif"))






## 세계식품



sgsp_plus_g = sgsp_plus
sgsp_plus_g = sgsp_plus_g %>% group_by(itemname, yearmonth) %>% summarise(qty_sum = sum(qty))
sgsp_plus_g$int_date = gsub("-","",sgsp_plus_g$yearmonth)
sgsp_plus_g$int_date = as.integer(sgsp_plus_g$int_date)
sgsp_plus_g = as.data.frame(sgsp_plus_g)


v1=seq(201501,201512,1)
v2=seq(201601,201612,1)
v3=seq(201701,201712,1)
v4=seq(201801,201812,1)
v5=seq(201901,201912,1)
v6=seq(202001,202003,1)

all_dt = c(v1,v2,v3,v4,v5,v6)
class(all_dt)
all_dt = as.data.frame(all_dt)
names(all_dt) = "int_date"


item_uniq = sgsp_plus_g$itemname %>% unique()


full_date_df = data.frame()
for(i in 1:length(item_uniq)) {
  si = sgsp_plus_g %>% filter(itemname == item_uniq[i])
  mer = left_join(all_dt, si)
  mer$itemname = unique(si$itemname)
  mer$qty_sum[is.na(mer$qty_sum) == T] = 0
  full_date_df = rbind(full_date_df, mer)
  
}

cum_sgsp = data.frame()



for(i in 1:(length(item_uniq))) {
  temp = full_date_df %>% filter(itemname == item_uniq[i])
  temp = temp %>% arrange(int_date)
  temp$qum_sum = cumsum(temp$qty_sum)
  
  cum_sgsp = rbind(cum_sgsp, temp)
  print(i)
}

cum_sgsp = cum_sgsp %>% group_by(int_date) %>% mutate(rank = min_rank(-qum_sum)*1,
                                           Value_rel = qum_sum/qum_sum[rank==1],
                                           Value_lbl = paste0(" ",qum_sum)) %>%
  filter(rank <= 30) %>% 
  ungroup()


p2 <- ggplot(cum_sgsp, aes(rank, group = itemname, 
                     fill = as.factor(itemname), color = as.factor(itemname))) +
  geom_tile(aes(y = qum_sum/2,
                height = qum_sum,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(itemname, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=qum_sum,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "발주량",
       caption = "Sources: World food | Plot generated Hyeon Jong") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,3,1,6, "cm")) +
  
  transition_states(int_date, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

animate(p2, 200, fps = 10, duration = 40, width = 1200, height = 800, renderer = gifski_renderer("gganim_sgsp_dcr_full.gif"))





sgsp_plus %>% as.data.table()
theme_set(theme_classic())
sgsp_plus_g = sgsp_plus
sgsp_plus_g = sgsp_plus_g %>% group_by(custname, yearmonth) %>% summarise(qty_sum = sum(qty))
sgsp_plus_g$int_date = gsub("-","",sgsp_plus_g$yearmonth)
sgsp_plus_g$int_date = as.integer(sgsp_plus_g$int_date)
sgsp_plus_g = as.data.frame(sgsp_plus_g)


unique_goods =  unique(sgsp_plus_g$custname)
cum_sgsp = data.frame()



for(i in 1:(length(unique_goods))) {
  temp = sgsp_plus_g %>% filter(custname == unique_goods[i])
  temp = temp %>% arrange(int_date)
  temp$qum_sum = cumsum(temp$qty_sum)
  
  cum_sgsp = rbind(cum_sgsp, temp)
  print(i)
}

cum_sgsp = cum_sgsp %>% group_by(int_date) %>% mutate(rank = min_rank(-qum_sum)*1,
                                                      Value_rel = qum_sum/qum_sum[rank==1],
                                                      Value_lbl = paste0(" ",qum_sum)) %>%
  filter(rank <= 20) %>% 
  ungroup()


p2 <- ggplot(cum_sgsp, aes(rank, group = custname, 
                           fill = as.factor(custname), color = as.factor(custname))) +
  geom_tile(aes(y = qum_sum/2,
                height = qum_sum,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(custname, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=qum_sum,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "발주량",
       caption = "Sources: World food | Plot generated Hyeon Jong") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,3,1,6, "cm")) +
  
  transition_states(int_date, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

animate(p2, 200, fps = 10, duration = 40, width = 1200, height = 800, renderer = gifski_renderer("gganim_sgsp_custname.gif"))






## 머거본

mgb_plus_j = mgb_plus
mgb_plus_j = left_join(date_df, mgb_plus)
mgb_plus_j[is.na(mgb_plus_j$qty),]$qty = 0



mgb_plus_j$custclass %>% unique()
mgb_plus_g = mgb_plus_j %>% filter(custclass == "오비맥주")
mgb_plus_g = mgb_plus_g %>% group_by(itemname, yearmonth) %>% summarise(qty_sum = sum(qty))
mgb_plus_g$int_date = gsub("-","",mgb_plus_g$yearmonth)
mgb_plus_g$int_date = as.integer(mgb_plus_g$int_date)
mgb_plus_g = as.data.frame(mgb_plus_g)



v1=seq(201501,201512,1)
v2=seq(201601,201612,1)
v3=seq(201701,201712,1)
v4=seq(201801,201812,1)
v5=seq(201901,201912,1)
v6=seq(202001,202003,1)

all_dt = c(v1,v2,v3,v4,v5,v6)
class(all_dt)
all_dt = as.data.frame(all_dt)
names(all_dt) = "int_date"


item_uniq = mgb_plus_g$itemname %>% unique()


full_date_df = data.frame()
for(i in 1:length(item_uniq)) {
  si = mgb_plus_g %>% filter(itemname == item_uniq[i])
  mer = left_join(all_dt, si)
  mer$itemname = unique(si$itemname)
  mer$qty_sum[is.na(mer$qty_sum) == T] = 0
  full_date_df = rbind(full_date_df, mer)
  
}

cum_sgsp = data.frame()

for(i in 1:(length(item_uniq))) {
  temp = full_date_df %>% filter(itemname == item_uniq[i])
  temp = temp %>% arrange(int_date)
  temp$qum_sum = cumsum(temp$qty_sum)
  
  cum_sgsp = rbind(cum_sgsp, temp)
  print(i)
}
cum_sgsp

cum_sgsp = cum_sgsp %>% group_by(int_date) %>% mutate(rank = min_rank(-qum_sum)*1,
                                                      Value_rel = qum_sum/qum_sum[rank==1],
                                                      Value_lbl = paste0(" ",qum_sum)) %>% 
  filter(rank <= 10) %>% 
  ungroup()


p3 <- ggplot(cum_sgsp, aes(rank, group = itemname, 
                           fill = as.factor(itemname), color = as.factor(itemname))) +
  geom_tile(aes(y = qum_sum/2,
                height = qum_sum,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(itemname, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=qum_sum,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "발주량",
       caption = "Sources: World food | Plot generated Hyeon Jong") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,3,1,6, "cm")) +
  
  transition_states(int_date, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

setwd("E:/data-analysis/ankus/ankus-lite-ver2/gminder")
animate(p3, 200, fps = 10, duration = 40, width = 1200, height = 800, renderer = gifski_renderer("gganim_mgb_obmj_full.gif"))





## 홍선



hs_plus
hs_plus_g = hs_plus 
hs_plus_g = hs_plus_g %>% group_by(itemname, yearmonth) %>% summarise(qty_sum = sum(qty))
hs_plus_g$int_date = gsub("-","",hs_plus_g$yearmonth)
hs_plus_g$int_date = as.integer(hs_plus_g$int_date)
hs_plus_g = as.data.frame(hs_plus_g)



v3=seq(201701,201712,1)
v4=seq(201801,201812,1)
v5=seq(201901,201912,1)
v6=seq(202001,202003,1)

all_dt = c(v3,v4,v5,v6)
class(all_dt)
all_dt = as.data.frame(all_dt)
names(all_dt) = "int_date"


item_uniq = hs_plus_g$itemname %>% unique()


full_date_df = data.frame()
for(i in 1:length(item_uniq)) {
  si = hs_plus_g %>% filter(itemname == item_uniq[i])
  mer = left_join(all_dt, si)
  mer$itemname = unique(si$itemname)
  mer$qty_sum[is.na(mer$qty_sum) == T] = 0
  full_date_df = rbind(full_date_df, mer)
  
}

cum_sgsp = data.frame()

for(i in 1:(length(item_uniq))) {
  temp = full_date_df %>% filter(itemname == item_uniq[i])
  temp = temp %>% arrange(int_date)
  temp$qum_sum = cumsum(temp$qty_sum)
  
  cum_sgsp = rbind(cum_sgsp, temp)
  print(i)
}


cum_sgsp = cum_sgsp %>% group_by(int_date) %>% mutate(rank = min_rank(-qum_sum)*1,
                                                      Value_rel = qum_sum/qum_sum[rank==1],
                                                      Value_lbl = paste0(" ",qum_sum)) %>% 
  filter(rank <= 20) %>% 
  ungroup()


p4 <- ggplot(cum_sgsp, aes(rank, group = itemname, 
                           fill = as.factor(itemname), color = as.factor(itemname))) +
  geom_tile(aes(y = qum_sum/2,
                height = qum_sum,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(itemname, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=qum_sum,label = Value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "발주량",
       caption = "Sources: World food | Plot generated Hyeon Jong") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(1,3,1,6, "cm")) +
  
  transition_states(int_date, transition_length = 4, state_length = 1) +
  ease_aes('cubic-in-out')

animate(p4, 200, fps = 10, duration = 40, width = 1200, height = 800, renderer = gifski_renderer("gganim_hs20_full.gif"))























